clear all; close all; clc;
workspace;

load('D:\figures\Bikent_01\features_spt.mat');
load('D:\figures\Bikent_01\features_temp.mat');
B_Mov1_spt(:,:)     = features_spt(:,:);
B_Mov1_temp(:,:)    = features_temp(:,:);
load('D:\figures\Bikent_02\features_spt.mat');
load('D:\figures\Bikent_02\features_temp.mat');
B_Mov2_spt(:,:)          = features_spt(:,:);
B_Mov2_temp(:,:)         = features_temp(:,:);
load('D:\figures\Bikent_03\features_spt.mat');
load('D:\figures\Bikent_03\features_temp.mat');
B_Mov3_spt(:,:)          = features_spt(:,:);
B_Mov3_temp(:,:)         = features_temp(:,:);
load('D:\figures\Bikent_04\features_spt.mat');
load('D:\figures\Bikent_04\features_temp.mat');
B_Mov4_spt(:,:)          = features_spt(:,:);
B_Mov4_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Bikent_05\features_spt.mat');
load('D:\figures\Bikent_05\features_temp.mat');
B_Mov5_spt(:,:)          = features_spt(:,:);
B_Mov5_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Bikent_06\features_spt.mat'); 
load('D:\figures\Bikent_06\features_temp.mat');
B_Mov6_spt(:,:)          = features_spt(:,:);
B_Mov6_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Bikent_07\features_spt.mat');
load('D:\figures\Bikent_07\features_temp.mat');
B_Mov7_spt(:,:)          = features_spt(:,:);
B_Mov7_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Bikent_08\features_spt.mat');
load('D:\figures\Bikent_08\features_temp.mat');
B_Mov8_spt(:,:)          = features_spt(:,:);
B_Mov8_temp(:,:)         = features_temp(:,:); 

load('D:\figures\Visor_01\features_spt.mat'); 
load('D:\figures\Visor_01\features_temp.mat');
V_Mov1_spt(:,:)          = features_spt(:,:);
V_Mov1_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Visor_02\features_spt.mat'); 
load('D:\figures\Visor_02\features_temp.mat');
V_Mov2_spt(:,:)          = features_spt(:,:);
V_Mov2_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Visor_03\features_spt.mat'); 
load('D:\figures\Visor_03\features_temp.mat');
V_Mov3_spt(:,:)          = features_spt(:,:);
V_Mov3_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Visor_04\features_spt.mat');
load('D:\figures\Visor_04\features_temp.mat');
V_Mov4_spt(:,:)          = features_spt(:,:);
V_Mov4_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Visor_05\features_spt.mat'); 
load('D:\figures\Visor_05\features_temp.mat');
V_Mov5_spt(:,:)          = features_spt(:,:);
V_Mov5_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Visor_06\features_spt.mat'); 
load('D:\figures\Visor_06\features_temp.mat');
V_Mov6_spt(:,:)          = features_spt(:,:);
V_Mov6_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Visor_07\features_spt.mat'); 
load('D:\figures\Visor_07\features_temp.mat');
V_Mov7_spt(:,:)          = features_spt(:,:);
V_Mov7_temp(:,:)         = features_temp(:,:); 
load('D:\figures\Visor_08\features_spt.mat'); 
load('D:\figures\Visor_08\features_temp.mat');
V_Mov8_spt(:,:)          = features_spt(:,:);
V_Mov8_temp(:,:)         = features_temp(:,:); 

save('D:\Lab Project Files\V_3\Featurevector\B_Mov1_spt.mat','B_Mov1_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov2_spt.mat','B_Mov2_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov3_spt.mat','B_Mov3_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov4_spt.mat','B_Mov4_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov5_spt.mat','B_Mov5_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov6_spt.mat','B_Mov6_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov7_spt.mat','B_Mov7_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov8_spt.mat','B_Mov8_spt');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov1_temp.mat','B_Mov1_temp');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov2_temp.mat','B_Mov2_temp');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov3_temp.mat','B_Mov3_temp');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov4_temp.mat','B_Mov4_temp');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov5_temp.mat','B_Mov5_temp');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov6_temp.mat','B_Mov6_temp');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov7_temp.mat','B_Mov7_temp');
save('D:\Lab Project Files\V_3\Featurevector\B_Mov8_temp.mat','B_Mov8_temp');

save('D:\Lab Project Files\V_3\Featurevector\V_Mov1_spt.mat','V_Mov1_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov2_spt.mat','V_Mov2_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov3_spt.mat','V_Mov3_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov4_spt.mat','V_Mov4_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov5_spt.mat','V_Mov5_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov6_spt.mat','V_Mov6_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov7_spt.mat','V_Mov7_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov8_spt.mat','V_Mov8_spt');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov1_temp.mat','V_Mov1_temp');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov2_temp.mat','V_Mov2_temp');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov3_temp.mat','V_Mov3_temp');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov4_temp.mat','V_Mov4_temp');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov5_temp.mat','V_Mov5_temp');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov6_temp.mat','V_Mov6_temp');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov7_temp.mat','V_Mov7_temp');
save('D:\Lab Project Files\V_3\Featurevector\V_Mov8_temp.mat','V_Mov8_temp');
